default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: myapp_production

  cable:
    <<: *default
    database: myapp_cable_production
